mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml,classpath*:/mapper/**/*.xml
  type-aliases-package: com.watchball.dataserver.*.entity.*,com.watchball.dataserver.*.dto
  global-config:
#    db-config:
#      id-type: id_worker_str
#      logic-delete-value: 1
#      logic-not-delete-value: 0
    banner: false
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.32.241:3306/view_ball?serverTimezone=GMT%2b8:00&useSSL=false&characterEncoding=UTF8&useUnicode=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 712yqf
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 200
      idle-timeout: 60000
      max-lifetime: 60000
